FROM nvcr.io/nvidia/pytorch:21.11-py3


RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt update && apt install -y  libssl-dev
RUN pip3 install -U pip

RUN git clone https://github.com/ultralytics/yolov5 --branch v6.0
RUN pip3 install -r yolov5/requirements.txt
RUN pip3 install roboflow tqdm albumentations

ENTRYPOINT ["jupyter", "lab","--ip=0.0.0.0","--allow-root"]
